// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sliceActVV.proto

package sliceActVV

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserActInfo struct {
	RtUClick             *int64   `protobuf:"varint,1,opt,name=rt_u_click" json:"rt_u_click,omitempty"`
	RtUReveal            *int64   `protobuf:"varint,2,opt,name=rt_u_reveal" json:"rt_u_reveal,omitempty"`
	RtURpt               *float64 `protobuf:"fixed64,3,opt,name=rt_u_rpt" json:"rt_u_rpt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserActInfo) Reset()         { *m = UserActInfo{} }
func (m *UserActInfo) String() string { return proto.CompactTextString(m) }
func (*UserActInfo) ProtoMessage()    {}
func (*UserActInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ad79fa5a82e28f4, []int{0}
}

func (m *UserActInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserActInfo.Unmarshal(m, b)
}
func (m *UserActInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserActInfo.Marshal(b, m, deterministic)
}
func (m *UserActInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserActInfo.Merge(m, src)
}
func (m *UserActInfo) XXX_Size() int {
	return xxx_messageInfo_UserActInfo.Size(m)
}
func (m *UserActInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserActInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserActInfo proto.InternalMessageInfo

func (m *UserActInfo) GetRtUClick() int64 {
	if m != nil && m.RtUClick != nil {
		return *m.RtUClick
	}
	return 0
}

func (m *UserActInfo) GetRtUReveal() int64 {
	if m != nil && m.RtUReveal != nil {
		return *m.RtUReveal
	}
	return 0
}

func (m *UserActInfo) GetRtURpt() float64 {
	if m != nil && m.RtURpt != nil {
		return *m.RtURpt
	}
	return 0
}

type FeedActInfo struct {
	RtFClick             *int64   `protobuf:"varint,1,opt,name=rt_f_click" json:"rt_f_click,omitempty"`
	RtFReveal            *int64   `protobuf:"varint,2,opt,name=rt_f_reveal" json:"rt_f_reveal,omitempty"`
	RtFRpt               *float64 `protobuf:"fixed64,3,opt,name=rt_f_rpt" json:"rt_f_rpt,omitempty"`
	RtF_2HClick          *int64   `protobuf:"varint,4,opt,name=rt_f_2h_click" json:"rt_f_2h_click,omitempty"`
	RtF_2HReveal         *int64   `protobuf:"varint,5,opt,name=rt_f_2h_reveal" json:"rt_f_2h_reveal,omitempty"`
	RtF_2HRpt            *float64 `protobuf:"fixed64,6,opt,name=rt_f_2h_rpt" json:"rt_f_2h_rpt,omitempty"`
	RtF_4HClick          *int64   `protobuf:"varint,7,opt,name=rt_f_4h_click" json:"rt_f_4h_click,omitempty"`
	RtF_4HReveal         *int64   `protobuf:"varint,8,opt,name=rt_f_4h_reveal" json:"rt_f_4h_reveal,omitempty"`
	RtF_4HRpt            *float64 `protobuf:"fixed64,9,opt,name=rt_f_4h_rpt" json:"rt_f_4h_rpt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedActInfo) Reset()         { *m = FeedActInfo{} }
func (m *FeedActInfo) String() string { return proto.CompactTextString(m) }
func (*FeedActInfo) ProtoMessage()    {}
func (*FeedActInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ad79fa5a82e28f4, []int{1}
}

func (m *FeedActInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedActInfo.Unmarshal(m, b)
}
func (m *FeedActInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedActInfo.Marshal(b, m, deterministic)
}
func (m *FeedActInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedActInfo.Merge(m, src)
}
func (m *FeedActInfo) XXX_Size() int {
	return xxx_messageInfo_FeedActInfo.Size(m)
}
func (m *FeedActInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedActInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FeedActInfo proto.InternalMessageInfo

func (m *FeedActInfo) GetRtFClick() int64 {
	if m != nil && m.RtFClick != nil {
		return *m.RtFClick
	}
	return 0
}

func (m *FeedActInfo) GetRtFReveal() int64 {
	if m != nil && m.RtFReveal != nil {
		return *m.RtFReveal
	}
	return 0
}

func (m *FeedActInfo) GetRtFRpt() float64 {
	if m != nil && m.RtFRpt != nil {
		return *m.RtFRpt
	}
	return 0
}

func (m *FeedActInfo) GetRtF_2HClick() int64 {
	if m != nil && m.RtF_2HClick != nil {
		return *m.RtF_2HClick
	}
	return 0
}

func (m *FeedActInfo) GetRtF_2HReveal() int64 {
	if m != nil && m.RtF_2HReveal != nil {
		return *m.RtF_2HReveal
	}
	return 0
}

func (m *FeedActInfo) GetRtF_2HRpt() float64 {
	if m != nil && m.RtF_2HRpt != nil {
		return *m.RtF_2HRpt
	}
	return 0
}

func (m *FeedActInfo) GetRtF_4HClick() int64 {
	if m != nil && m.RtF_4HClick != nil {
		return *m.RtF_4HClick
	}
	return 0
}

func (m *FeedActInfo) GetRtF_4HReveal() int64 {
	if m != nil && m.RtF_4HReveal != nil {
		return *m.RtF_4HReveal
	}
	return 0
}

func (m *FeedActInfo) GetRtF_4HRpt() float64 {
	if m != nil && m.RtF_4HRpt != nil {
		return *m.RtF_4HRpt
	}
	return 0
}

func init() {
	proto.RegisterType((*UserActInfo)(nil), "userActInfo")
	proto.RegisterType((*FeedActInfo)(nil), "feedActInfo")
}

func init() { proto.RegisterFile("sliceActVV.proto", fileDescriptor_1ad79fa5a82e28f4) }

var fileDescriptor_1ad79fa5a82e28f4 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd0, 0xcb, 0x4a, 0xc4, 0x30,
	0x14, 0xc6, 0x71, 0xe2, 0x78, 0x19, 0x4f, 0x51, 0x86, 0x88, 0x92, 0x95, 0x0c, 0xb3, 0x9a, 0x85,
	0x64, 0x21, 0x7d, 0x81, 0x76, 0xa5, 0x6b, 0xa1, 0xdb, 0xd2, 0xc6, 0x44, 0x43, 0x63, 0x13, 0xd3,
	0x53, 0xc1, 0xb7, 0xf4, 0x91, 0xa4, 0xe9, 0x65, 0x08, 0x74, 0xfb, 0xe7, 0x9c, 0xdf, 0xe2, 0x83,
	0x5d, 0x67, 0xb4, 0x90, 0x99, 0xc0, 0xa2, 0xe0, 0xce, 0x5b, 0xb4, 0x87, 0x17, 0x48, 0xfa, 0x4e,
	0xfa, 0x4c, 0xe0, 0x6b, 0xab, 0x2c, 0xa5, 0x00, 0x1e, 0xcb, 0xbe, 0x14, 0x46, 0x8b, 0x86, 0x91,
	0x3d, 0x39, 0x6e, 0xe8, 0x1d, 0x24, 0xa1, 0x79, 0xf9, 0x23, 0x2b, 0xc3, 0xce, 0x42, 0xdc, 0xc1,
	0x76, 0x8c, 0x0e, 0xd9, 0x66, 0x4f, 0x8e, 0xe4, 0xf0, 0x47, 0x20, 0x51, 0x52, 0xbe, 0xc7, 0x94,
	0x5a, 0xa1, 0xd4, 0x1a, 0xa5, 0x4e, 0x14, 0xbd, 0x87, 0x9b, 0x50, 0x9e, 0x3f, 0xa7, 0xef, 0xf3,
	0x70, 0xf8, 0x00, 0xb7, 0x73, 0x9e, 0x80, 0x8b, 0x48, 0x1d, 0xba, 0x43, 0x76, 0x19, 0x19, 0xe9,
	0x6c, 0x5c, 0x45, 0x46, 0xba, 0x18, 0xdb, 0xc8, 0x48, 0x47, 0xe3, 0x7a, 0x30, 0xf2, 0x27, 0x78,
	0x14, 0xf6, 0x8b, 0xeb, 0x6f, 0xfd, 0xab, 0x39, 0x62, 0xed, 0x2b, 0xdd, 0x72, 0x63, 0x3f, 0xb8,
	0x32, 0xba, 0x6d, 0xb8, 0xab, 0x73, 0x78, 0x5b, 0x06, 0xfd, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xf2,
	0x20, 0xa5, 0x8b, 0x5d, 0x01, 0x00, 0x00,
}
